<?php

use Mockery as m;
use Way\Tests\Factory;

class AssignExceptionsTest extends TestCase {

	public function __construct()
	{
		$this->mock = m::mock('Eloquent', 'Assign_exception');
		$this->collection = m::mock('Illuminate\Database\Eloquent\Collection')->shouldDeferMissing();
	}

	public function setUp()
	{
		parent::setUp();

		$this->attributes = Factory::assign_exception(['id' => 1]);
		$this->app->instance('Assign_exception', $this->mock);
	}

	public function tearDown()
	{
		m::close();
	}

	public function testIndex()
	{
		$this->mock->shouldReceive('all')->once()->andReturn($this->collection);
		$this->call('GET', 'assign_exceptions');

		$this->assertViewHas('assign_exceptions');
	}

	public function testCreate()
	{
		$this->call('GET', 'assign_exceptions/create');

		$this->assertResponseOk();
	}

	public function testStore()
	{
		$this->mock->shouldReceive('create')->once();
		$this->validate(true);
		$this->call('POST', 'assign_exceptions');

		$this->assertRedirectedToRoute('assign_exceptions.index');
	}

	public function testStoreFails()
	{
		$this->mock->shouldReceive('create')->once();
		$this->validate(false);
		$this->call('POST', 'assign_exceptions');

		$this->assertRedirectedToRoute('assign_exceptions.create');
		$this->assertSessionHasErrors();
		$this->assertSessionHas('message');
	}

	public function testShow()
	{
		$this->mock->shouldReceive('findOrFail')
				   ->with(1)
				   ->once()
				   ->andReturn($this->attributes);

		$this->call('GET', 'assign_exceptions/1');

		$this->assertViewHas('assign_exception');
	}

	public function testEdit()
	{
		$this->collection->id = 1;
		$this->mock->shouldReceive('find')
				   ->with(1)
				   ->once()
				   ->andReturn($this->collection);

		$this->call('GET', 'assign_exceptions/1/edit');

		$this->assertViewHas('assign_exception');
	}

	public function testUpdate()
	{
		$this->mock->shouldReceive('find')
				   ->with(1)
				   ->andReturn(m::mock(['update' => true]));

		$this->validate(true);
		$this->call('PATCH', 'assign_exceptions/1');

		$this->assertRedirectedTo('assign_exceptions/1');
	}

	public function testUpdateFails()
	{
		$this->mock->shouldReceive('find')->with(1)->andReturn(m::mock(['update' => true]));
		$this->validate(false);
		$this->call('PATCH', 'assign_exceptions/1');

		$this->assertRedirectedTo('assign_exceptions/1/edit');
		$this->assertSessionHasErrors();
		$this->assertSessionHas('message');
	}

	public function testDestroy()
	{
		$this->mock->shouldReceive('find')->with(1)->andReturn(m::mock(['delete' => true]));

		$this->call('DELETE', 'assign_exceptions/1');
	}

	protected function validate($bool)
	{
		Validator::shouldReceive('make')
				->once()
				->andReturn(m::mock(['passes' => $bool]));
	}
}
